export type Team = {
  id: string;
  name: string;
  league: string;
  competition: string;
  country: string;
  shortName: string;
  accent: string;
};

export const TEAM_CATALOG: Team[] = [
  { id: "paok", name: "PAOK", league: "Super League", competition: "Super League", country: "Greece", shortName: "PAOK", accent: "#1e3a8a" },
  { id: "ael", name: "AEL", league: "Super League", competition: "Super League", country: "Greece", shortName: "AEL", accent: "#b91c1c" },
  { id: "aek", name: "AEK Athens", league: "Super League", competition: "Super League", country: "Greece", shortName: "AEK", accent: "#0ea5e9" },
  { id: "aris", name: "Aris", league: "Super League", competition: "Super League", country: "Greece", shortName: "ARI", accent: "#facc15" },
  { id: "asteras-tripolis", name: "Asteras Tripolis", league: "Super League", competition: "Super League", country: "Greece", shortName: "AST", accent: "#facc15" },
  { id: "atromitos", name: "Atromitos", league: "Super League", competition: "Super League", country: "Greece", shortName: "ATR", accent: "#22d3ee" },
  { id: "kifisia", name: "Kifisia", league: "Super League", competition: "Super League", country: "Greece", shortName: "KIF", accent: "#16a34a" },
  { id: "levadiakos", name: "Levadiakos", league: "Super League", competition: "Super League", country: "Greece", shortName: "LEV", accent: "#15803d" },
  { id: "olympiacos", name: "Olympiacos", league: "Super League", competition: "Super League", country: "Greece", shortName: "OLY", accent: "#f59e0b" },
  { id: "ofi", name: "OFI", league: "Super League", competition: "Super League", country: "Greece", shortName: "OFI", accent: "#111827" },
  { id: "panetolikos", name: "Panetolikos", league: "Super League", competition: "Super League", country: "Greece", shortName: "PAN", accent: "#facc15" },
  { id: "panathinaikos", name: "Panathinaikos", league: "Super League", competition: "Super League", country: "Greece", shortName: "PAN", accent: "#22c55e" },
  { id: "panserraikos", name: "Panserraikos", league: "Super League", competition: "Super League", country: "Greece", shortName: "PAN", accent: "#dc2626" },
  { id: "volos", name: "Volos", league: "Super League", competition: "Super League", country: "Greece", shortName: "VOL", accent: "#dc2626" },

  { id: "aston-villa", name: "Aston Villa", league: "Premier League", competition: "Premier League", country: "England", shortName: "AVL", accent: "#7c3aed" },
  { id: "bournemouth", name: "Bournemouth", league: "Premier League", competition: "Premier League", country: "England", shortName: "BOU", accent: "#dc2626" },
  { id: "brentford", name: "Brentford", league: "Premier League", competition: "Premier League", country: "England", shortName: "BRE", accent: "#dc2626" },
  { id: "brighton", name: "Brighton", league: "Premier League", competition: "Premier League", country: "England", shortName: "BRI", accent: "#2563eb" },
  { id: "burnley", name: "Burnley", league: "Premier League", competition: "Premier League", country: "England", shortName: "BUR", accent: "#7f1d1d" },
  { id: "liverpool", name: "Liverpool", league: "Premier League", competition: "Premier League", country: "England", shortName: "LIV", accent: "#c8102e" },
  { id: "crystal-palace", name: "Crystal Palace", league: "Premier League", competition: "Premier League", country: "England", shortName: "CRY", accent: "#1d4ed8" },
  { id: "everton", name: "Everton", league: "Premier League", competition: "Premier League", country: "England", shortName: "EVE", accent: "#1d4ed8" },
  { id: "fulham", name: "Fulham", league: "Premier League", competition: "Premier League", country: "England", shortName: "FUL", accent: "#f8fafc" },
  { id: "leeds", name: "Leeds United", league: "Premier League", competition: "Premier League", country: "England", shortName: "LEE", accent: "#f8fafc" },
  { id: "arsenal", name: "Arsenal", league: "Premier League", competition: "Premier League", country: "England", shortName: "ARS", accent: "#ef4444" },
  { id: "chelsea", name: "Chelsea", league: "Premier League", competition: "Premier League", country: "England", shortName: "CHE", accent: "#1d4ed8" },
  { id: "man-city", name: "Manchester City", league: "Premier League", competition: "Premier League", country: "England", shortName: "MCI", accent: "#6ee7b7" },
  { id: "manchester-united", name: "Manchester United", league: "Premier League", competition: "Premier League", country: "England", shortName: "MUN", accent: "#dc2626" },
  { id: "newcastle", name: "Newcastle United", league: "Premier League", competition: "Premier League", country: "England", shortName: "NEW", accent: "#f8fafc" },
  { id: "nottingham-forest", name: "Nottingham Forest", league: "Premier League", competition: "Premier League", country: "England", shortName: "NFO", accent: "#dc2626" },
  { id: "sunderland", name: "Sunderland", league: "Premier League", competition: "Premier League", country: "England", shortName: "SUN", accent: "#dc2626" },
  { id: "tottenham", name: "Tottenham Hotspur", league: "Premier League", competition: "Premier League", country: "England", shortName: "TOT", accent: "#f8fafc" },
  { id: "west-ham", name: "West Ham United", league: "Premier League", competition: "Premier League", country: "England", shortName: "WHU", accent: "#7c2d12" },
  { id: "wolverhampton", name: "Wolverhampton Wanderers", league: "Premier League", competition: "Premier League", country: "England", shortName: "WOL", accent: "#f59e0b" },

  { id: "augsburg", name: "Augsburg", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "FCA", accent: "#dc2626" },
  { id: "borussia-dortmund", name: "Borussia Dortmund", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "BVB", accent: "#f3b30d" },
  { id: "bayern-munich", name: "Bayern Munich", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "BAY", accent: "#e11d48" },
  { id: "werder-bremen", name: "Werder Bremen", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "SVW", accent: "#16a34a" },
  { id: "eintracht-frankfurt", name: "Eintracht Frankfurt", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "SGE", accent: "#dc2626" },
  { id: "freiburg", name: "Freiburg", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "SCF", accent: "#dc2626" },
  { id: "hamburg", name: "Hamburg", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "HSV", accent: "#2563eb" },
  { id: "heidenheim", name: "Heidenheim", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "HDH", accent: "#dc2626" },
  { id: "hoffenheim", name: "Hoffenheim", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "TSG", accent: "#2563eb" },
  { id: "koln", name: "Koln", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "KOE", accent: "#dc2626" },
  { id: "mainz", name: "Mainz 05", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "M05", accent: "#dc2626" },
  { id: "borussia-monchengladbach", name: "Borussia Monchengladbach", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "BMG", accent: "#f8fafc" },
  { id: "rb-leipzig", name: "RB Leipzig", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "RBL", accent: "#f97316" },
  { id: "bayer-leverkusen", name: "Bayer Leverkusen", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "LEV", accent: "#84cc16" },
  { id: "st-pauli", name: "St. Pauli", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "STP", accent: "#78350f" },
  { id: "stuttgart", name: "VfB Stuttgart", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "VFB", accent: "#f8fafc" },
  { id: "union-berlin", name: "Union Berlin", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "FCU", accent: "#dc2626" },
  { id: "wolfsburg", name: "Wolfsburg", league: "Bundesliga", competition: "Bundesliga", country: "Germany", shortName: "WOB", accent: "#65a30d" },

  { id: "alaves", name: "Alaves", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "ALA", accent: "#2563eb" },
  { id: "athletic-bilbao", name: "Athletic Bilbao", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "ATH", accent: "#dc2626" },
  { id: "real-madrid", name: "Real Madrid", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "RMA", accent: "#f1f5f9" },
  { id: "barcelona", name: "Barcelona", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "BAR", accent: "#0f766e" },
  { id: "atletico-madrid", name: "Atletico Madrid", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "ATM", accent: "#f43f5e" },
  { id: "celta-vigo", name: "Celta Vigo", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "CEL", accent: "#38bdf8" },
  { id: "elche", name: "Elche", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "ELC", accent: "#16a34a" },
  { id: "espanyol", name: "Espanyol", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "ESP", accent: "#2563eb" },
  { id: "getafe", name: "Getafe", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "GET", accent: "#2563eb" },
  { id: "girona", name: "Girona", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "GIR", accent: "#dc2626" },
  { id: "mallorca", name: "Mallorca", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "MLL", accent: "#dc2626" },
  { id: "rayo-vallecano", name: "Rayo Vallecano", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "RAY", accent: "#dc2626" },
  { id: "real-sociedad", name: "Real Sociedad", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "RSO", accent: "#facc15" },
  { id: "osasuna", name: "Osasuna", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "OSA", accent: "#dc2626" },
  { id: "real-betis", name: "Real Betis", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "BET", accent: "#16a34a" },
  { id: "sevilla", name: "Sevilla", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "SEV", accent: "#dc2626" },
  { id: "valencia", name: "Valencia", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "VAL", accent: "#f59e0b" },
  { id: "villarreal", name: "Villarreal", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "VIL", accent: "#facc15" },
  { id: "levante", name: "Levante", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "LEV", accent: "#2563eb" },
  { id: "oviedo", name: "Real Oviedo", league: "LaLiga", competition: "LaLiga", country: "Spain", shortName: "OVI", accent: "#2563eb" },

  { id: "atalanta", name: "Atalanta", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "ATA", accent: "#2563eb" },
  { id: "inter", name: "Inter Milan", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "INT", accent: "#0f172a" },
  { id: "juventus", name: "Juventus", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "JUV", accent: "#f8fafc" },
  { id: "ac-milan", name: "AC Milan", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "MIL", accent: "#dc2626" },
  { id: "bologna", name: "Bologna", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "BOL", accent: "#dc2626" },
  { id: "cagliari", name: "Cagliari", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "CAG", accent: "#dc2626" },
  { id: "como", name: "Como", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "COM", accent: "#38bdf8" },
  { id: "cremonese", name: "Cremonese", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "CRE", accent: "#dc2626" },
  { id: "fiorentina", name: "Fiorentina", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "FIO", accent: "#7c3aed" },
  { id: "genoa", name: "Genoa", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "GEN", accent: "#dc2626" },
  { id: "lazio", name: "Lazio", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "LAZ", accent: "#38bdf8" },
  { id: "napoli", name: "Napoli", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "NAP", accent: "#3b82f6" },
  { id: "lecce", name: "Lecce", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "LEC", accent: "#facc15" },
  { id: "parma", name: "Parma", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "PAR", accent: "#7c3aed" },
  { id: "pisa", name: "Pisa", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "PIS", accent: "#2563eb" },
  { id: "roma", name: "Roma", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "ROM", accent: "#f59e0b" },
  { id: "sassuolo", name: "Sassuolo", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "SAS", accent: "#16a34a" },
  { id: "torino", name: "Torino", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "TOR", accent: "#dc2626" },
  { id: "udinese", name: "Udinese", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "UDI", accent: "#f8fafc" },
  { id: "verona", name: "Verona", league: "Serie A", competition: "Serie A", country: "Italy", shortName: "VER", accent: "#facc15" },

  { id: "alverca", name: "Alverca", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "ALV", accent: "#dc2626" },
  { id: "avs", name: "AVS", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "AVS", accent: "#facc15" },
  { id: "arouca", name: "Arouca", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "ARO", accent: "#facc15" },
  { id: "benfica", name: "Benfica", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "BEN", accent: "#e11d48" },
  { id: "casa-pia", name: "Casa Pia", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "CPI", accent: "#111827" },
  { id: "estoril", name: "Estoril", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "EST", accent: "#facc15" },
  { id: "estrela-amadora", name: "Estrela Amadora", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "EST", accent: "#f8fafc" },
  { id: "famalicao", name: "Famalicao", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "FAM", accent: "#2563eb" },
  { id: "gil-vicente", name: "Gil Vicente", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "GIL", accent: "#dc2626" },
  { id: "moreirense", name: "Moreirense", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "MOR", accent: "#16a34a" },
  { id: "nacional", name: "Nacional", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "NAC", accent: "#111827" },
  { id: "porto", name: "Porto", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "POR", accent: "#fbbf24" },
  { id: "rio-ave", name: "Rio Ave", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "RIO", accent: "#16a34a" },
  { id: "sporting-cp", name: "Sporting CP", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "SPO", accent: "#22c55e" },
  { id: "santa-clara", name: "Santa Clara", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "SAN", accent: "#dc2626" },
  { id: "tondela", name: "Tondela", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "TON", accent: "#facc15" },
  { id: "vitoria-guimaraes", name: "Vitoria Guimaraes", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "VIT", accent: "#111827" },
  { id: "braga", name: "Braga", league: "Primeira Liga", competition: "Primeira Liga", country: "Portugal", shortName: "BRA", accent: "#f97316" },
];

export function validateTeamSelection(teamIds: string[]) {
  const unique = [...new Set(teamIds)];
  const validIds = new Set(TEAM_CATALOG.map((team) => team.id));
  const normalized = unique.filter((id) => validIds.has(id)).slice(0, 3);

  return normalized;
}
